---
#ansible-playbook -i hosts ssh-copy-id.yml -u root -k --extra-vars "usuario=sysadmin"

- hosts: all
  become: yes
  become_user: root

  vars:
    password: $6$23iakq8EIMvczdUi$psY2MljWGE/9PPwmtTReoXGI6r8K6gZpDNx26IcdgLoxAeu9GHNOLddmf4NbG3L53zlMZpHg3pVOV7OXBIfym.

  tasks:

    - name: create user sysadmin and put on sudoers
      user: name=sysadmin
            state=present
            group=wheel
            groups=wheel
            password={{password}}
[root@ansible roles]# cat ssh-copy-id.yml
---
- name: configure passwordless ssh authentication on a remote machine
  hosts: localhost

- hosts: all
  user: root
  tasks:
    - authorized_key:
        user: "{{ usuario }}"
        state: present
        key: "{{ lookup('file', '/var/lib/jenkins/.ssh/id_rsa.pub') }}"
